### ISSUE TITLE
Retrieve API Version from request

### ISSUE THREAD

**Issue by ferenc-hechler** [phenixblue/imageswap-webhook#80]
**What happened**:

Due to an mistake I created PODs with apiVersion "v1beta1" instead of "v1".
In my Kubernetes cluster everything worked well, but the Webhook had no effect. 
In the logfile I could see, that it was active and working, but the created but was unmodified.

**What you expected to happen**:

The POD should have been created with the imageswap modifications.

**How to reproduce it (as minimally and precisely as possible)**:

Create a POD with apiKind "v1beta1" and an image, which is mapped by Image-Swap.

```
apiVersion: v1beta1
kind: Pod
metadata:
  name: demopod
spec:
  containers:
    - name: demopod
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
```

In the Image-Swap debuglog of the "Admission Review" you see that the field "apiVersion" of the response is set to "v1".
Kubernetes seems to ignore this modification and the POD is created without the Image-Swap modifications.

- Kubernetes version (use `kubectl version`):

Kubernetes v1.21

- Cloud provider or hardware configuration:

AWS EKS
